# Generated by Django 4.0.2 on 2022-02-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='abc'),
        ),
    ]
