# Generated by Django 2.1.5 on 2022-02-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='abc', upload_to='uploads/images/'),
        ),
    ]
