# Generated by Django 2.1.5 on 2022-02-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/images/')),
                ('code', models.TextField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='components.Category')),
            ],
        ),
    ]
