# Generated by Django 2.1.5 on 2022-02-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='code',
        ),
        migrations.RemoveField(
            model_name='note',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
