# Generated by Django 2.1.5 on 2022-02-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_auto_20220210_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description1',
            new_name='description',
        ),
    ]
