# Generated by Django 2.1.5 on 2022-02-10 06:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20220210_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
